config/routes.rb
SMU::Application.routes.draw do

  get "dashboard/index"
  get "group_schedules/index"
  get "group_schedules/new/:id", :controller => "group_schedules", :action => "new", as: "group_schedule_new"
  get "group_schedules/edit"
  get "group_schedules/create"
  patch "group_schedules/update"

  resources :addresses

  resources :organizations

  resources :schedules

  resources :groups

  devise_for :users
  scope :admin do
    resources :users
  end

  get "/about_us" => "home#about"
  get "/contact_us" => "home#contact"
  get "/help" => "home#help"

  authenticated do
    root :to => "dashboard#index", :as => "signed_in_root"
  end
  unauthenticated do
    root :to => "home#index"
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :schedules, :through => :users
  has_one :user
  belongs_to :organization
  accepts_nested_attributes_for :schedules
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new(:organization_id => params[:organization_id])
    @users = User.where(:group_id => @group.id)

  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:organization_id, :name, :organization)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
            <% @group.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <form class="form-inline" role="form">
      <div class="form-group" style="display: inline-flex">
        <%= f.hidden_field :organization_id, class: 'form-control', placeholder: 'Organization #' %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
      <button name="commit" type="submit" class="btn btn-primary">Create</button>
    </form>
<% end %>

app/views/groups/_groups.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Group Name</th>
    <th>Manager</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.user.lastname unless group.user.nil? %></td>
        <td><%= link_to group do %> <span class="glyphicon glyphicon-eye-open"></span> <% end %> </td>
        <td><%= link_to edit_group_path(group) do %><span class="glyphicon glyphicon-pencil"></span> <% end %></td>
        <td><%= link_to group, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove"></span> <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<%= render partial: 'groups/groups' %>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>
<%= @group.organization.name unless @group.organization.nil? %>
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1 id="type-default"><%= @group.name %></h1>
        <ul class="nav nav-pills">
          <li class="active"><%= link_to '+ User', new_user_path(:group_id => @group.id)%></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">Employees</div>
        <div class="panel-body">
          <% if @users %>
              <%= render partial: 'users/users' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>