config/routes.rb
SMU::Application.routes.draw do

  get "dashboard/index"
  get "group_schedules/index"
  get "group_schedules/new/:id", :controller => "group_schedules", :action => "new", as: "group_schedule_new"
  get "group_schedules/edit"
  get "group_schedules/create"
  patch "group_schedules/update"

  resources :addresses

  resources :organizations

  resources :schedules

  resources :groups

  devise_for :users
  scope :admin do
    resources :users
  end

  get "/about_us" => "home#about"
  get "/contact_us" => "home#contact"
  get "/help" => "home#help"

  authenticated do
    root :to => "dashboard#index", :as => "signed_in_root"
  end
  unauthenticated do
    root :to => "home#index"
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @schedule }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:user_id, :mon, :tues, :wed, :thur, :fri, :sat, :sun)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
    <% if @schedule.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @schedule.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <form class="form-inline" role="form">
        <div class="form-group" style="display: inline-flex">
          <%= f.number_field :user_id, class: 'form-control', label: 'user' %>
          <%= f.text_field :sun, class: 'form-control', placeholder: 'Sun' %>
          <%= f.text_field :mon, class: 'form-control', placeholder: 'Mon' %>
          <%= f.text_field :tues, class: 'form-control', placeholder: 'Tu' %>
          <%= f.text_field :wed, class: 'form-control', placeholder: 'We' %>
          <%= f.text_field :thur, class: 'form-control', placeholder: 'Thu' %>
          <%= f.text_field :fri, class: 'form-control', placeholder: 'Fri' %>
          <%= f.text_field :sat, class: 'form-control', placeholder: 'Sat' %>
        </div>
      <button name="commit" type="submit" class="btn btn-primary">Create</button>
    </form>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Mon</th>
      <th>Tues</th>
      <th>Wed</th>
      <th>Thur</th>
      <th>Fri</th>
      <th>Sat</th>
      <th>Sun</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= "#{schedule.user.lastname}, #{schedule.user.firstname}" %></td>
        <td><%= schedule.mon %></td>
        <td><%= schedule.tues %></td>
        <td><%= schedule.wed %></td>
        <td><%= schedule.thur %></td>
        <td><%= schedule.fri %></td>
        <td><%= schedule.sat %></td>
        <td><%= schedule.sun %></td>
        <td><%= link_to schedule do %> <span class="glyphicon glyphicon-eye-open"></span> <% end %> </td>
        <td><%= link_to edit_schedule_path(schedule) do %><span class="glyphicon glyphicon-pencil"></span> <% end %></td>
        <td><%= link_to schedule, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove"></span> <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

app/views/schedules/show.html.erb
<p>
  <strong>User:</strong>
  <%= @schedule.user_id %>
</p>

<p>
  <strong>Mon:</strong>
  <%= @schedule.mon %>
</p>

<p>
  <strong>Tues:</strong>
  <%= @schedule.tues %>
</p>

<p>
  <strong>Wed:</strong>
  <%= @schedule.wed %>
</p>

<p>
  <strong>Thur:</strong>
  <%= @schedule.thur %>
</p>

<p>
  <strong>Fri:</strong>
  <%= @schedule.fri %>
</p>

<p>
  <strong>Sat:</strong>
  <%= @schedule.sat %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @schedule.sun %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>