config/routes.rb
SMU::Application.routes.draw do

  get "dashboard/index"
  get "group_schedules/index"
  get "group_schedules/new/:id", :controller => "group_schedules", :action => "new", as: "group_schedule_new"
  get "group_schedules/edit"
  get "group_schedules/create"
  patch "group_schedules/update"

  resources :addresses

  resources :organizations

  resources :schedules

  resources :groups

  devise_for :users
  scope :admin do
    resources :users
  end

  get "/about_us" => "home#about"
  get "/contact_us" => "home#contact"
  get "/help" => "home#help"

  authenticated do
    root :to => "dashboard#index", :as => "signed_in_root"
  end
  unauthenticated do
    root :to => "home#index"
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:user_id, :state, :city, :street, :zip)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_addresses.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>User</th>
    <th>State</th>
    <th>City</th>
    <th>Street</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @addresses.each do |address| %>
      <tr>
        <td><%= address.user_id %></td>
        <td><%= address.state %></td>
        <td><%= address.city %></td>
        <td><%= address.street %></td>
        <td><%= address.zip %></td>
        <td><%= link_to address do %> <span class="glyphicon glyphicon-eye-open"></span> <% end %> </td>
        <td><%= link_to edit_address_path(address) do %><span class="glyphicon glyphicon-pencil"></span> <% end %></td>
        <td><%= link_to address, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove"></span> <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/addresses/_form.html.erb
<%= simple_form_for(@address) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :state %>
    <%= f.input :city %>
    <%= f.input :street %>
    <%= f.input :zip %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<%= render partial: 'addresses/addresses' %>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

app/views/addresses/show.html.erb
<p>
  <strong>User:</strong>
  <%= User.where(id: @address.user_id) %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @address.zip %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>