config/routes.rb
SMU::Application.routes.draw do

  get "dashboard/index"
  get "group_schedules/index"
  get "group_schedules/new/:id", :controller => "group_schedules", :action => "new", as: "group_schedule_new"
  get "group_schedules/edit"
  get "group_schedules/create"
  patch "group_schedules/update"

  resources :addresses

  resources :organizations

  resources :schedules

  resources :groups

  devise_for :users
  scope :admin do
    resources :users
  end

  get "/about_us" => "home#about"
  get "/contact_us" => "home#contact"
  get "/help" => "home#help"

  authenticated do
    root :to => "dashboard#index", :as => "signed_in_root"
  end
  unauthenticated do
    root :to => "home#index"
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_one :user
  has_many :groups
  has_one :address, through: :user
  has_many :users
  after_create :add_default_manager!
  after_create :add_default_group!


  def add_default_manager!
    new_admin = User.create do |user|
      user.email = "change_me#{User.count + 1}@smu.com"
      user.firstname = "Default"
      user.lastname = "User"
      user.role = "admin"
      user.password = "changeme"
      user.organization_id = self.id
    end
    self.user_id = new_admin.id
  end

  def add_default_group!
    Group.create do |group|
      group.name = "default group"
      group.organization_id = self.id
      group.user_id = self.user.id
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @groups = Group.where(:organization_id => @organization.id)
    @users = User.where(:organization_id => @organization.id)
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
    <% if @organization.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @organization.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <form class="form-inline" role="form">
      <div class="form-group" style="display: inline-flex">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
      <button name="commit" type="submit" class="btn btn-primary">Create</button>
    </form>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manager</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.user.lastname unless organization.user.nil? %></td>
        <td><%= link_to organization do %> <span class="glyphicon glyphicon-eye-open"></span> <% end %> </td>
        <td><%= link_to edit_organization_path(organization) do %><span class="glyphicon glyphicon-pencil"></span> <% end %></td>
        <td><%= link_to organization, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove"></span> <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

app/views/organizations/show.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1 id="type-default"><%= @organization.name %></h1>
        <ul class="nav nav-pills">
          <li class="active"><%= link_to '+ Group', new_group_path(:organization_id => @organization.id)%></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">My Groups</div>
        <div class="panel-body">
          <% if @groups %>
              <%= render partial: "groups/groups" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading">My Employees</div>
        <div class="panel-body">
          <% if @users %>
              <%= render partial: 'users/users' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>